### ISSUE TITLE
[backend] kubeflow 1.6.0 no support onExit

### ISSUE THREAD

**Issue by yiyuanyu17** [kubeflow/pipelines#7009]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
kubeflow 1.6.0

### Steps to reproduce
I write a pipeline with on exit component  and I can upload to kubeflow 1.0, but when I  use 1.6.0 kubeflow, 
![image](https://user-images.githubusercontent.com/15135974/144860628-6fcc5c2a-8cee-4a42-a9c2-f71f4163b7cf.png)
but when comment the 
![image](https://user-images.githubusercontent.com/15135974/144861131-e52a8abe-5eb0-4339-ba6a-9756d1c4088f.png)
it can be upload to kubeflow 1.6.0 and missing the datasync component

**Comment by yiyuanyu17** [comment]
here is our test pipeline


`import os
import sys

import kfp.compiler
import kfp.components as comp
import kfp.dsl as dsl
import json

start_comp = comp.load_component_from_file('./start.yaml')
work_comp = comp.load_component_from_file('./work.yaml')
exit_comp = comp.load_component_from_file('./exit.yaml')


@dsl.pipeline(
    name="[test]exit test pipeline"
)
def pipeline(
    task_id: int
):

    pipeline_conf = dsl.get_pipeline_conf()
    pipeline_conf.set_image_pull_secrets([{"name": "rudder-image-secret"}])
    pipeline_conf.set_image_pull_policy("Always")
    pipeline_conf.set_ttl_seconds_after_finished(7200)  # one day


    exit_op = exit_comp(str(task_id)).set_display_name("onExit")

    with dsl.ExitHandler(exit_op):
        start_op = start_comp().set_display_name("start")
        work_op = work_comp().set_display_name("work")
        work_op.after(start_op)



if __name__ == '__main__':

    kfp.compiler.Compiler().compile(pipeline, __file__.rstrip('.py') + '.yaml')
`
and the start.yaml, work.yaml, exit.yaml  provided here
start.yaml
`name: start
inputs:
outputs:
implementation:
  container:
    image: busybox
    args: [
      '/bin/sh',
      '-c',
      'echo pipeline start'
    ]
`
work.yaml
`name: work
inputs:
outputs:
implementation:
  container:
    image: busybox
    args: [
      '/bin/sh',
      '-c',
      'echo working... ;sleep 10; echo done'
    ]
`
exit.yaml
`name: exit
inputs:
  - {name: task_id, type: String, description: 'task id'}
outputs:
implementation:
  container:
    image: busybox
    args: [
      '/bin/sh',
      '-c',
      'echo pipeline exit',
      {inputValue: task_id}
    ]
`
and use kfp 1.6.0  which can be uploaded in kubeflow 1.0, but can not be uploaded in kubeflow 1.6

**Comment by yiyuanyu17** [comment]
hi ,is there any progress ?@ji-yaqi

**Comment by ji-yaqi** [comment]
Hi @yiyuanyu17, could you update your SDK version to 1.8.10 (latest)? We have fixed a bunch of bugs since 1.6.0. 
Your code can compile in 1.8.10 with no errors.

**Comment by yiyuanyu17** [comment]
> Hi @yiyuanyu17, could you update your SDK version to 1.8.10 (latest)? We have fixed a bunch of bugs since 1.6.0. Your code can compile in 1.8.10 with no errors.

if we update sdk version to 1.8.10, the yaml will work with kubeflow 1.0?

**Comment by yiyuanyu17** [comment]
> 

@ji-yaqi  we test sdk 1.8.10, and still have the error

**Comment by ji-yaqi** [comment]
@yiyuanyu17 Do you have compilation error or upload error? I started on a clean version of 1.8.10 and doesn't have the compilation error. Maybe try force-reinstall the package?

**Comment by yiyuanyu17** [comment]
> @yiyuanyu17 Do you have compilation error or upload error? I started on a clean version of 1.8.10 and doesn't have the compilation error. Maybe try force-reinstall the package?

@ji-yaqi  
![image](https://user-images.githubusercontent.com/15135974/145662849-cd8981a1-0ec4-4f02-b634-547682e9f051.png)
i reinstall the kfp==1.8.10 , and upload to the kubeflow 1.6.0. and the error still is 

```
{
    "error_message": "Error creating pipeline version: Create pipeline version failed: Failed to get parameters from the workflow: templates.exit inputs.parameters.task_id was not supplied",
    "error_details": "templates.exit inputs.parameters.task_id was not supplied\ngithub.com/argoproj/argo-workflows/v3/errors.New\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.0/errors/errors.go:49\ngithub.com/argoproj/argo-workflows/v3/errors.Errorf\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.0/errors/errors.go:55\ngithub.com/argoproj/argo-workflows/v3/workflow/validate.(*templateValidationCtx).validateTemplate\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.0/workflow/validate/validate.go:340\ngithub.com/argoproj/argo-workflows/v3/workflow/validate.(*templateValidationCtx).validateTemplateHolder\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.0/workflow/validate/validate.go:454\ngithub.com/argoproj/argo-workflows/v3/workflow/validate.ValidateWorkflow\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.0/workflow/validate/validate.go:210\ngithub.com/kubeflow/pipelines/backend/src/common/util.ValidateWorkflow\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/template_util.go:60\ngithub.com/kubeflow/pipelines/backend/src/common/util.GetParameters\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/template_util.go:31\ngithub.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).CreatePipelineVersion\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/resource/resource_manager.go:1153\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineUploadServer).UploadPipelineVersion\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/pipeline_upload_server.go:185\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nFailed to get parameters from the workflow\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:275\ngithub.com/kubeflow/pipelines/backend/src/common/util.GetParameters\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/template_util.go:33\ngithub.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).CreatePipelineVersion\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/resource/resource_manager.go:1153\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineUploadServer).UploadPipelineVersion\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/pipeline_upload_server.go:185\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nCreate pipeline version failed\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:275\ngithub.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).CreatePipelineVersion\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/resource/resource_manager.go:1155\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineUploadServer).UploadPipelineVersion\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/pipeline_upload_server.go:185\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nError creating pipeline version\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:275\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineUploadServer).UploadPipelineVersion\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/pipeline_upload_server.go:199\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"
}
```

**Comment by ji-yaqi** [comment]
I see. 

We will need community help on this issue: add `task_id` to exit handler in KFP V1. 
Workaround: manually add param in generated yaml file.

**Comment by yiyuanyu17** [comment]
> ssue: add

it's ok if manually add param in generated yaml file, but it's our product environment, and our actual pipeline is more complex than the demo. so we need help to solve this bug by client. @ji-yaqi  @james-jwu

**Comment by yiyuanyu17** [comment]
> > ssue: add
> 
> it's ok if manually add param in generated yaml file, but it's our product environment, and our actual pipeline is more complex than the demo. so we need help to solve this bug by client. @ji-yaqi @james-jwu

we want to upgrade our kubeflow to 1.6.0  to use the new functions of kf1.6.0, and we have many pipelines generate by python code,  and we use exit hander to do some postprocess in any condition.   If we manually add param in generated yaml file, it will be heavy work to modify each pipeline 。 @james-jwu

**Comment by chensun** [comment]
I investigate a bit, there's no behavior change from KFP SDK side.
Here's a simplified yaml I tried, it works on kfp 1.4.1 but not on 1.7.0
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-pipeline-
spec:
  entrypoint: test-pipeline
  templates:
  - name: exit
    container:
      args: ['echo {{inputs.parameters.task_id}}']
      command: [/bin/sh, -c]
      image: busybox
    inputs:
      parameters:
      - {name: task_id}
  - name: exit-handler-1
    dag:
      tasks:
      - {name: start, template: start}
  - name: start
    container:
      args: [echo pipeline start]
      command: [/bin/sh, -c]
      image: busybox
  - name: test-pipeline
    dag:
      tasks:
      - {name: exit-handler-1, template: exit-handler-1}
  arguments:
    parameters:
    - name: task_id
#     if I add `value` for the parameter, then it can pass validation
#     value: something
  serviceAccountName: pipeline-runner
  onExit: exit
```
I believe this is a regression from Argo side, and opened https://github.com/argoproj/argo-workflows/issues/7424

While waiting for Argo's fix, there's another workaround for you: give `task_id` a default value like such:
```
@dsl.pipeline(
    name="[test]exit test pipeline"
)
def pipeline(
    task_id: int = 0 #  just give it any dummy value, which will be override by the actual value you provide at submission time.
):
```

This should be much easier than modifying the generated yaml file.

**Comment by yiyuanyu17** [comment]
thanks, we will try to add the default value . @chensun

**Comment by ittus** [comment]
I encountered a same issue. Setting default value to python function helps.

Deployment:
```
kfp pipeline 1.8.1
gcr.io/ml-pipeline/api-server:1.8.1)
gcr.io/ml-pipeline/argoexec:v3.2.3-license-compliance
```

Client:
```
kfp==1.8.12
kfp-api-server==1.8.1
```

**Comment by casassg** [comment]
+1 here, do we know if there's any way to fix it from kfp side (by providing some sort of default when param is being used on ExitHandler?) Or  by at least failing more gracefully on Compiler if ExitOp contains a param w no default?

**Comment by rimolive** [comment]
Closing this issue as there's no activity for more than a year. Feel free to open it if the issue persists in kfp 2.0.5

/close

**Comment by tom-pavz** [comment]
/reopen

I still see this issue with kfp SDK 1.8.22 and backend `2.1.0`
