### ISSUE TITLE
[bug] .after() raises error if task it is applied to has any arguments

### ISSUE THREAD

**Issue by bogdanCsn** [kubeflow/pipelines#10594]
### Environment

*  KFP version: 2.7.0

### Steps to reproduce

The pipeline below fails to compile using `kfp==2.7.0` but it does compile (and work properly with `kfp==2.2.0` )

```
from kfp import dsl, compiler

@dsl.component
def loop_function():
    return "foo"

@dsl.component
def standalone_function():
    return "bar"

@dsl.component
def standalone_function_with_args(cfg: dict):
    return "bar"

@dsl.pipeline()
def pipe_main(cfg: dict):

    with dsl.ParallelFor(items=[1, 5, 10], parallelism=2) as i:
        task1 = loop_function()

    task2 = standalone_function_with_args(cfg=cfg)
    task2.after(task1)
```
The error received at compile time is `AttributeError: 'NoneType' object has no attribute 'name'`

If the function that creates `task2` doesn't take any arguments, the compilation occurs without any errors. The number of arguments or their type (tested with int, str, dict) does not seem to matter.
```
    task2 = standalone_function()
    task2.after(task1)
```

### Expected result
The pipeline should compile without any errors irrespective of the number of arguments.

### Labels
/area sdk

---

Impacted by this bug? Give it a 👍.

**Comment by jsilva** [comment]
I got the same issue and reported in https://github.com/kubeflow/pipelines/issues/10592.

This a big blocker for us, now.

**Comment by bogdanCsn** [comment]
@jsilva I'm using a workaround for the time being - a different pipeline that just runs the loop. Obviously not an ideal solution, but this works:

```
@dsl.component
def loop_function():
    return "foo"

@dsl.component
def standalone_function():
    return "bar"

@dsl.component
def standalone_function_with_args(cfg: dict):
    return "bar"

@dsl.pipeline()
def dummy_pipe():
    with dsl.ParallelFor(items=[1, 5, 10], parallelism=2) as i:
        loop_task = loop_function()


@dsl.pipeline()
def pipe_main(cfg: dict):

	task1 = dummy_pipe()
	
    task2 = standalone_function_with_args(cfg=cfg)
    task2.after(task1)
```

**Comment by jsilva** [comment]
This bug is still present in SDK 2.2.0.
