### PR TITLE
fix(sdk): resolve kfp.dsl.pipeline_context circular import. Fixes #12522

### LINKED ISSUE #12522: [backend] Strange Behavior After 2.15.1 released
### Environment

VertexAI Pipelines

### Steps to reproduce

Define a function that imports the DSL components in a function component like this

```python
from kfp.dsl import Output, Dataset, Model, Artifact, Metrics

def dataset_op(
    test_dataset: Output[Dataset],
    training_dataset: Output[Dataset],
    validation_dataset: Output[Dataset],
    brand: str, 
    config: Dict,                  
): 
    from kfp.dsl import Output, Dataset, Model, Artifact, Metrics 

    # By removing the internal imports it works as expected

    def some_fn( test_dataset: Output[Dataset],  training_dataset: Output[Dataset],   validation_dataset: Output[Dataset]):
        ....

    some_fn(test_dataset, training_dataset, validation_dataset)
```

yields the following error

AttributeError: partially initialized module 'kfp.dsl.pipeline_context' has no attribute 'Pipeline' (most likely due to a circular reference)

File "/usr/local/lib/python3.10/site-packages/kfp/dsl/graph_component.py", line 141, in GraphComponent

### Expected result

I would expect it to work just like it did prior to the 1.15 release. I understand this might not be correct usage of the API. What we built was an abstraction around KFP pipelines where a user supplies a configuration pointing to a sdist package and we invoke the users function from a dynamically generated KFP python component.

Here is the code generated

```python
@dsl.component(
    base_image=intrpl(global_dataset_op_config["image"]),
    packages_to_install=intrpl(global_dataset_op_config["packages_to_install"]),
    pip_index_urls=intrpl(global_dataset_op_config["pip_index_urls"]),
)
def dataset_sdist_op(
    config: Dict,
    brand: str,
    training_dataset: dsl.Output[dsl.Dataset],
    test_dataset: dsl.Output[dsl.Dataset],
    validation_dataset: dsl.Output[dsl.Dataset],
) -> bool:
    import logging
    import os
    from mlutils.support import get_dataset_op_config, get_function_to_invoke

    logging.basicConfig(level=logging.DEBUG)
    logger = logging.getLogger(__name__)
    logger.info("ENV: [%s]", os.environ)
    logger.info("Config: [%s]", config)

    dataset_op_config = config

    logger.info("Config dataset_op_config: [%s]", dataset_op_config)

    fn = get_function_to_invoke(
        dataset_op_config["module"], dataset_op_config["function"]
    )
    return fn(test_dataset, training_dataset, validation_dataset, brand, config)
```

Here is the function in the sdist

```python
import os
from kfp.dsl import Output, Dataset, Model, Artifact, Metrics
from typing import Dict, NamedTuple

def dataset_op(
    test_dataset: Output[Dataset],
    training_dataset: Output[Dataset],
    validation_dataset: Output[Dataset],
    brand: str, 
    config: Dict,                  
):  
   ...
```

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by shivv23**
**Description of your changes:**

Fixes #12522.

Under `_KFP_RUNTIME=true` (e.g., when the Kubeflow Pipelines runtime or Vertex AI executes a pipeline function), importing `kfp.dsl.graph_component` or `kfp.dsl.pipeline_context` raised:

```
AttributeError: partially initialized module 'kfp.dsl.pipeline_context' has no attribute 'Pipeline' (most likely due to a circular import)
```

The failure was caused by a circular import between the `kfp.dsl` package and the `kfp.compiler` package:

- `graph_component.py` imported `kfp.compiler.pipeline_spec_builder` at module import time, which pulls in `kfp.compiler.compiler_utils`, which imports `kfp.dsl.pipeline_context`, which imports `kfp.dsl.component_factory`, which imports `kfp.dsl.graph_component` (still partially initialized), and an eagerly evaluated return annotation (`-> graph_component.GraphComponent`) crashed.
- The regression was introduced by #12234, which added `_validate_workspace_requirements` with an eagerly evaluated `pipeline: pipeline_context.Pipeline` parameter annotation in `graph_component.py`.

Changes:

- `sdk/python/kfp/dsl/graph_component.py`: import `kfp.compiler.pipeline_spec_builder` lazily inside `__init__` instead of at module import time, breaking the circular import at its source; add `from __future__ import annotations` to defer annotation evaluation.
- `sdk/python/kfp/dsl/component_factory.py`: add `from __future__ import annotations` so the `-> graph_component.GraphComponent` return annotation is no longer evaluated eagerly.
- `sdk/python/kfp/dsl/base_component.py`: import `pipeline_context` lazily inside `__call__` (its only use), removing the `base_component -> pipeline_context -> component_factory -> container_component_class/python_component -> base_component` cycle from the DSL-internal import graph.
- `sdk/python/kfp/dsl/graph_component_test.py`: new regression test that imports `kfp.dsl.graph_component` and `kfp.dsl.pipeline_context` in subprocesses with `_KFP_RUNTIME=true`.

**Checklist:**
- [x] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by droctothorpe** [comment]
Hi @shivv23, thank you for your PR! The linked issue (#12522) must be labeled `ready` before your contribution can be reviewed. Please check our [CONTRIBUTING.md](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md) for details.
