### PR TITLE
fix(backend): pass dagTasks to resolveInputParameter in the DRA claim path. Fixes #14388

### LINKED ISSUE #14388: bug(backend): master does not compile, driver k8s.go:323 misses the dagTasks argument
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? Not deployed. This is a build failure on `master`, reproduced by compiling the backend from a fresh checkout.
*  KFP version: `master` at ba3ed8f06fe567dcb1037df321e434b452c76440
*  KFP SDK version: not applicable, the failure is in the Go backend.

### Steps to reproduce

`backend/src/v2/driver` does not compile on `master`, so the driver binary cannot be built:

```
$ git log -1 --format='%h %s'
ba3ed8f perf(backend): read the DAG tree once per driver resolution pass (#14338)
$ go build ./backend/src/v2/driver/
# github.com/kubeflow/pipelines/backend/src/v2/driver
backend/src/v2/driver/k8s.go:323:36: not enough arguments in call to resolveInputParameter
	have (context.Context, *metadata.DAG, *metadata.Pipeline, Options, *metadata.Client, *pipelinespec.TaskInputsSpec_InputParameterSpec, map[string]*structpb.Value)
	want (context.Context, *metadata.DAG, *metadata.Pipeline, Options, *metadata.Client, *pipelinespec.TaskInputsSpec_InputParameterSpec, map[string]*structpb.Value, *dagTaskCache)
```

`go vet ./backend/src/v2/driver/...` and `go test ./backend/src/v2/driver/...` fail the same way with `[build failed]`, which takes the whole `Test_extendPodSpecPatch_PodResourceClaims` table in `k8s_test.go` down with them.

The cause is a semantic merge conflict between two PRs that merged three days apart. #14243 (merged 2026-09-10) added the DRA call site at `backend/src/v2/driver/k8s.go:322-323`, inside `extendPodSpecPatch`, for the `PodResourceClaims` path. #14338 (merged 2026-09-13) added a trailing `dagTasks *dagTaskCache` parameter to `resolveInputParameter` at `backend/src/v2/driver/resolve.go:412` and updated the call sites present in its base, including the sibling toleration call at `k8s.go:245-246`, but #14243's newer call site was not in that base. Git merged both without a textual conflict; the compiler did not.

### Expected result

`master` compiles and `go test ./backend/src/v2/driver/...` runs. The cache is already in scope at the broken call site: `extendPodSpecPatch` creates it at `k8s.go:153` with `dagTasks := newDAGTaskCache()`, so passing `dagTasks` as the last argument restores the build and gives the DRA claim path the same per-patch DAG cache the toleration path already uses.

### Materials and Reference

The `KFP Backend Tests` workflow run for the push of ba3ed8f failed: https://github.com/kubeflow/pipelines/actions/runs/34780074059

### PR DESCRIPTION
**Pull request by rishabhsai**
**Description of your changes:**

`master` has not compiled since ba3ed8f0 (#14338): `go build ./backend/src/v2/driver/` fails at `backend/src/v2/driver/k8s.go:323` with "not enough arguments in call to resolveInputParameter", so the driver binary cannot be built from `master` and the `KFP Backend Tests` run for that push is red. #14243 added the DRA resource-claim call site inside `extendPodSpecPatch` on 2026-09-10, and #14338 added a trailing `dagTasks *dagTaskCache` parameter to `resolveInputParameter` on 2026-09-13 and updated the call sites present in its base, including the sibling toleration call at `k8s.go:245`, but #14243's newer call site was not in that base; the two merged without a textual conflict and the compiler caught what git did not. The cache is already created at `k8s.go:153`, so this passes it at the one call site that was missed, which also gives the claim path the same per-patch DAG cache the toleration path already uses. No test is added, because #14243 did ship coverage here: the 19-case `Test_extendPodSpecPatch_PodResourceClaims` table in `k8s_test.go` already exercises this call site through its "JSON component input" cases, and it simply could not run while the package failed to compile.

Fixes #14388

```
# before, at upstream/master ba3ed8f0
$ go build ./backend/src/v2/driver/
# github.com/kubeflow/pipelines/backend/src/v2/driver
backend/src/v2/driver/k8s.go:323:36: not enough arguments in call to resolveInputParameter
	have (context.Context, *metadata.DAG, *metadata.Pipeline, Options, *metadata.Client, *pipelinespec.TaskInputsSpec_InputParameterSpec, map[string]*structpb.Value)
	want (context.Context, *metadata.DAG, *metadata.Pipeline, Options, *metadata.Client, *pipelinespec.TaskInputsSpec_InputParameterSpec, map[string]*structpb.Value, *dagTaskCache)
$ go test ./backend/src/v2/driver/ -run Test_extendPodSpecPatch_PodResourceClaims -count=1
FAIL	github.com/kubeflow/pipelines/backend/src/v2/driver [build failed]

# after
$ go build ./backend/... && go vet ./backend/src/v2/driver/...
$ go test ./backend/src/v2/driver/... -count=1
ok  	github.com/kubeflow/pipelines/backend/src/v2/driver	1.653s
$ go test ./backend/src/v2/driver/ -run Test_extendPodSpecPatch_PodResourceClaims -count=1 -v | tail -3
    --- PASS: Test_extendPodSpecPatch_PodResourceClaims/Duplicate_with_pre-existing_podSpec_claim_-_error (0.00s)
PASS
ok  	github.com/kubeflow/pipelines/backend/src/v2/driver	0.933s

# repo backend unit suite (./test/presubmit-backend-test.sh command): 53 packages ok, 0 failures
```

Red CI on the offending push: https://github.com/kubeflow/pipelines/actions/runs/34780074059

**Checklist:**
- [x] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention)

### CODE REVIEW

**Comment by jeffspahr** [comment]
/approve
/lgtm

Thanks for the contribution @rishabhsai !

**Comment by rishabhsai** [comment]
exciting to get my first PR merged! will learn and contribute more! 

Thanks for the fast turnaround :)
