### ISSUE TITLE
[sdk] RBAC: access denied after following the documentation

### ISSUE THREAD

**Issue by khituras** [kubeflow/pipelines#9774]
### Environment

*  KFP version:
Full Kubeflow v1.7 on prem installation via https://github.com/kubeflow/manifests on K3s, Multi-User-Setup
*  KFP SDK version: 
2.0.0-alpha.7
*  All dependencies version:
kfp                           2.0.1
kfp-pipeline-spec             0.2.2
kfp-server-api                2.0.0

### Steps to reproduce
1. Follow instructions at https://www.kubeflow.org/docs/components/pipelines/v1/sdk/connect-api/#full-kubeflow-subfrom-inside-clustersub for Full Kubeflow including
  * Creation of PodDefaults in the user namespace
  * Creation of RBAC Authorization via
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-USERNS-kubeflow-edit
  ## this RoleBinding is in `namespace-1`, because it grants access to `namespace-1`
  namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-edit
subjects:
  - kind: ServiceAccount
    name: default-editor
    ## the ServiceAccount lives in `namespace-2`
    namespace: USERNS
```
2. Create a new Notebook server where specifying the PodDefaults above as the configuration
3. Make sure that the authorization token is actually present in the notebook server:
```
   /var/run/secrets/kubeflow/pipelines$ ls
  token
```
4. Create a new notebook with the following contents
```python
import kfp

# the namespace in which you deployed Kubeflow Pipelines
namespace = "kubeflow"

client = kfp.Client(host=f"http://ml-pipeline-ui.{namespace}")

print(client.list_experiments())
```

Executing this code should connect to the pipeline server and return the experiments. Instead, there is an error message:
```
ERROR:root:Failed to get healthz info attempt 1 of 5.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/kfp/client/client.py", line 435, in get_kfp_healthz
    return self._healthz_api.get_healthz()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Fri, 21 Jul 2023 13:10:37 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '1'})
HTTP response body: RBAC: access denied
```

### Expected result

This should have listed the experiments in my namespace.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by Linchin** [comment]
Hi @khituras, thank you for your question. I see from the instruction the command [also included the credential information](https://www.kubeflow.org/docs/components/pipelines/v1/sdk/connect-api/#full-kubeflow-subfrom-inside-clustersub:~:text=credentials%3Dcredentials)), maybe try adding it and see if it works? Feel free to reopen if you have any further problem.

**Comment by khituras** [comment]
Hello @Linchin and thank you very much for the answer. You're right, I did omit the credential information. This was because I was using kfp v2 where `kfp.auth` does not exist and I also didn't find a replacement.

I have now created a new notebook server where I use `kfp==1.8.22`. Unfortunately, the passing of credentials did not solve the issue. I think I must have some misconfiguration but I can't see it.

1. My Python code is now an exact copy&and paste from the instructions at https://www.kubeflow.org/docs/components/pipelines/v1/sdk/connect-api/#full-kubeflow-subfrom-inside-clustersub
2. I created the PodDefaults in my user profile namespace, just as shown in the instructions. I checked in OpenLens that they are present and in the right namespace.
3. I created a new notebook server that uses those PodDefaults as its configuration.
4. The notebook container has the `default-editor` service account: 
    ```yaml
       serviceAccountName: default-editor
       serviceAccount: default-editor
    ```
5. The ServiceAccount token is accessible in the notebook servier:
    ```bash
    $ ls /var/run/secrets/kubeflow/pipelines/
    token
    ```
6. I do use the token credentials in my Python code:
    ```python
    import kfp
    
    # the namespace in which you deployed Kubeflow Pipelines
    namespace = "kubeflow"
    
    # the KF_PIPELINES_SA_TOKEN_PATH environment variable is used when no `path` is set
    # the default KF_PIPELINES_SA_TOKEN_PATH is /var/run/secrets/kubeflow/pipelines/token
    credentials = kfp.auth.ServiceAccountTokenVolumeCredentials(path=None)
    
    client = kfp.Client(host=f"http://ml-pipeline-ui.{namespace}", credentials=credentials)
    
    print(client.list_experiments())
    ```
7. The RBAC authorization looks like it did before, I repeat it from above (of course, USERNS is set to my actual user profile namespace):
    ```yaml
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: allow-USERNS-kubeflow-edit
      ## this RoleBinding is in `namespace-1`, because it grants access to `namespace-1`
      namespace: kubeflow
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: kubeflow-edit
    subjects:
      - kind: ServiceAccount
        name: default-editor
        ## the ServiceAccount lives in `namespace-2`
        namespace: USERNS
    ```
8. There is a `default-editor` service account in my user namespace, it wasn't changed since profile creation
9. The `kubeflow-edit` cluster role also exists and was not changed since cluster creation. Here are the RBAC verbs currently set for `experiments` which (I think) need for my code example (perhaps there is another verb like 'read' or 'list' that I don't know about?):
    ```yaml
    - verbs:
      - archive
      - create
      - delete
      - unarchive
    apiGroups:
      - pipelines.kubeflow.org
    resources:
      - experiments
    ```

So I basically think it ought to work. Still, I get the error

```
ERROR:root:Failed to get healthz info attempt 1 of 5.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/kfp/_client.py", line 410, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Fri, 28 Jul 2023 07:41:12 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})
HTTP response body: RBAC: access denied
```

I notice that the HTTP response mentions `envoy`. Am I perhaps required to add configuration for Istio?

**Comment by khituras** [comment]
It seems I am not able to re-open the issue. Could you perhaps do it, @Linchin ?

**Comment by khituras** [comment]
I finally managed to solve this. The issue seems to be that in the full Kubeflow installation, Istio is also installed which takes precedence in authorization issues. Thus, the vanilla-Kubernetes RBAC `RoleBinding` seems not be used at all. In my current working setup it is not present in the cluster.
Instead, I edited the `AuthorizationPolicy´ CRD with name `ml-pipeline-ui` in the `kubeflow` namespace. It originally reads

```yaml
spec:
  rules:
    - from:
        - source:
            namespaces:
              - istio-system
  selector:
    matchLabels:
      app: ml-pipeline-ui
```
Per the Istio authorization policy rules (check out the very informative [policy precedence graph](https://istio.io/latest/docs/concepts/security/#implicit-enablement)) this means that the `ml-pipeline-ui` service only allows requests from the `istio-system` namespace. All that must be done is to add the namespace where your notebook server resides in - i.e. your kubeflow profile name - to the list right under `istio-system`.
Then, the access to the `ml-pipeline-ui` service is allowed and works. I successfully listed experiments and also submitted a pipeline.

**Comment by ntang86** [comment]
The above solution is for `kfp==1.8.22`. Anyone managed to make it work with `kfp=>2.0.0`?

**Comment by khituras** [comment]
This actually works for me with kfp == 2.0.0. not the beta but the release. I updated the Kubeflow deployment files to use the 2.0.0 images.
The only thing is that I had just leave the Kfp Host parameter empty when creating the Client. It’s not needed from within the Cluster.

**Comment by ntang86** [comment]
Thanks for the info, what image did you change in the kubeflow deployment? 
I'm running on 2.0.0-alpha.7 for the moment.
gcr.io/ml-pipeline/api-server:2.0.0-alpha.7
gcr.io/ml-pipeline/frontend:2.0.0-alpha.7

When running on kfp==2.0.0
I get `module 'kfp.components.structures' has no attribute 'ContainerSpecImplementation'`
When running on kfp==2.2.0
I get 
```
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=utf-8', 'x-content-type-options': 'nosniff', 'date': 'Thu, 21 Sep 2023 20:40:27 GMT', 'content-length': '10', 'x-envoy-upstream-service-time': '2', 'server': 'envoy'})
HTTP response body: Not Found
```

Code:
```
import kfp

client = kfp.Client()
print(client.list_experiments())
```

**Comment by khituras** [comment]
I replaced all image tags `2.0.0-alpha.7` with `2.0.0` That was actually quite a few places. I searched for the string `2.0.0-alpha.7` in the manifstests which worked because it seems the Kfp version is unique in Kubeflow 1.7. I found (probably not a complete list)
* gcr.io/ml-pipeline/api-server
* gcr.io/ml-pipeline/persistenceagent
* gcr.io/ml-pipeline/scheduledworkflow
* gcr.io/ml-pipeline/frontend
* gcr.io/ml-pipeline/viewer-crd-controller
* gcr.io/ml-pipeline/visualization-server
* gcr.io/ml-pipeline/metadata-envoy
* gcr.io/ml-pipeline/cache-deployer
* gcr.io/ml-pipeline/cache-server

It is quite possible that there is a better way of updating Kfp that I'm not aware of.
Anyway, using the updated deployment and `kfp>=2.1.3` with the PodDefaults etc. allows me in a Kubeflow Jupyter Notebook (that's important, for this to work the pipeline needs to be started from within the cluster):

```python`
def my_pipeline():
    ...

client = kfp.Client()

client.create_run_from_pipeline_func(my_pipeline, arguments={}, run_name="my_run", experiment_name="my_experiment")
```

Output:
```
/opt/conda/lib/python3.11/site-packages/kfp/client/client.py:158: FutureWarning: This client only works with Kubeflow Pipeline v2.0.0-beta.2 and later versions.
  warnings.warn(

[Experiment details](https://<my-domain>/pipeline/#/experiments/details/fb3f3ea6-0ec8-4310-92b5-0c605e87ee47).
[Run details](https:/<my-domain>/pipeline/#/runs/details/c03e2d21-941a-4f38-914d-a4fe48d1ac01).
```

**Comment by ntang86** [comment]
Thank you very much for the detailed explanation. 

I understand better how kfp and the ml-pipeline are interacting now. 

Indeed, it is very hard to keep up with all those changes and manually updating ml-pipeline images does not guarantee, it will not break the current Kubeflow installation. 

The most stable way is probably to map one Kubeflow release to **one** compatible kfp version. Did not find that in the documentation.

**Comment by zijianjoy** [comment]
Thank you for the investigation and instruction. Kubeflow Pipelines 2.0.0 will be released along side kubeflow 1.8 that is coming soon. Closing this item for now since the newer version has fixed the issue.

**Comment by jaffe-fly** [comment]
not work in `kfp 2.7.0` ,get error 
`kfp_server_api.exceptions.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'www-authenticate': 'Bearer realm="http://ml-pipeline.kubeflow.svc.cluster.local:8888/apis/v2beta1/healthz", error="invalid_token"', 'content-length': '28', 'content-type': 'text/plain', 'date': 'Sun, 14 Jul 2024 07:39:13 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})
HTTP response body: Jwt issuer is not configured`

> I finally managed to solve this. The issue seems to be that in the full Kubeflow installation, Istio is also installed which takes precedence in authorization issues. Thus, the vanilla-Kubernetes RBAC `RoleBinding` seems not be used at all. In my current working setup it is not present in the cluster. Instead, I edited the `AuthorizationPolicy` CRD with name `ml-pipeline-ui` in the `kubeflow` namespace. It originally reads
> 
> ```yaml
> spec:
>   rules:
>     - from:
>         - source:
>             namespaces:
>               - istio-system
>   selector:
>     matchLabels:
>       app: ml-pipeline-ui
> ```
> 
> Per the Istio authorization policy rules (check out the very informative [policy precedence graph](https://istio.io/latest/docs/concepts/security/#implicit-enablement)) this means that the `ml-pipeline-ui` service only allows requests from the `istio-system` namespace. All that must be done is to add the namespace where your notebook server resides in - i.e. your kubeflow profile name - to the list right under `istio-system`:
> 
> ```yaml
> spec:
>   rules:
>     - from:
>         - source:
>             namespaces:
>               - istio-system
>               - MY_NAMESPACE
>   selector:
>     matchLabels:
>       app: ml-pipeline-ui
> ```
> 
> Then, the access to the `ml-pipeline-ui` service is allowed and works. I successfully listed experiments and also submitted a pipeline.
