### ISSUE TITLE
bug(backend): master does not compile, driver k8s.go:323 misses the dagTasks argument

### ISSUE THREAD

**Issue by rishabhsai** [kubeflow/pipelines#14388]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? Not deployed. This is a build failure on `master`, reproduced by compiling the backend from a fresh checkout.
*  KFP version: `master` at ba3ed8f06fe567dcb1037df321e434b452c76440
*  KFP SDK version: not applicable, the failure is in the Go backend.

### Steps to reproduce

`backend/src/v2/driver` does not compile on `master`, so the driver binary cannot be built:

```
$ git log -1 --format='%h %s'
ba3ed8f perf(backend): read the DAG tree once per driver resolution pass (#14338)
$ go build ./backend/src/v2/driver/
# github.com/kubeflow/pipelines/backend/src/v2/driver
backend/src/v2/driver/k8s.go:323:36: not enough arguments in call to resolveInputParameter
	have (context.Context, *metadata.DAG, *metadata.Pipeline, Options, *metadata.Client, *pipelinespec.TaskInputsSpec_InputParameterSpec, map[string]*structpb.Value)
	want (context.Context, *metadata.DAG, *metadata.Pipeline, Options, *metadata.Client, *pipelinespec.TaskInputsSpec_InputParameterSpec, map[string]*structpb.Value, *dagTaskCache)
```

`go vet ./backend/src/v2/driver/...` and `go test ./backend/src/v2/driver/...` fail the same way with `[build failed]`, which takes the whole `Test_extendPodSpecPatch_PodResourceClaims` table in `k8s_test.go` down with them.

The cause is a semantic merge conflict between two PRs that merged three days apart. #14243 (merged 2026-09-10) added the DRA call site at `backend/src/v2/driver/k8s.go:322-323`, inside `extendPodSpecPatch`, for the `PodResourceClaims` path. #14338 (merged 2026-09-13) added a trailing `dagTasks *dagTaskCache` parameter to `resolveInputParameter` at `backend/src/v2/driver/resolve.go:412` and updated the call sites present in its base, including the sibling toleration call at `k8s.go:245-246`, but #14243's newer call site was not in that base. Git merged both without a textual conflict; the compiler did not.

### Expected result

`master` compiles and `go test ./backend/src/v2/driver/...` runs. The cache is already in scope at the broken call site: `extendPodSpecPatch` creates it at `k8s.go:153` with `dagTasks := newDAGTaskCache()`, so passing `dagTasks` as the last argument restores the build and gives the DRA claim path the same per-patch DAG cache the toleration path already uses.

### Materials and Reference

The `KFP Backend Tests` workflow run for the push of ba3ed8f failed: https://github.com/kubeflow/pipelines/actions/runs/34780074059
